//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrencyRate()
        {
            this.CurrencyName = new HashSet<CurrencyName>();
        }
    
        public int ID { get; set; }
        public string CurrencyClass { get; set; }
        public string CashBuy { get; set; }
        public string CashSell { get; set; }
        public string OnlineBuy { get; set; }
        public string OnlineSell { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrencyName> CurrencyName { get; set; }
    }
}
