//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund_data
    {
        public string Date { get; set; }
        public string MemberCode { get; set; }
        public string CompanyName { get; set; }
        public string FundID { get; set; }
        public string FundCode { get; set; }
        public string FundName { get; set; }
        public string FundNAV { get; set; }
        public string Fluctuate { get; set; }
        public string FluctuateRatio { get; set; }
        public string TypeCode { get; set; }
        public string Currancy { get; set; }
        public string BenifitCode { get; set; }
    }
}
